### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ocgltd** [Eccenux/POBS#2]
1. change POBS code to NOT use PHP's short_open_tag's (obsolete) - or make it a config option
2. change POBS code to not write PHP's short_open_tag style when writing comment
3. create an option to obfuscate the name of subdirectories (beneath root of source)
4. create an option to delete the target directory before starting (otherwise old files may be left behind)
5. allow POBS to run from command line, passing only the config/ini file name

**Comment by mstahl3** [comment]
and to add to that list...

6. The javascript processing needs work.  It is replacing standard javascript function names (which breaks the code, replacing string constants (eg: directory names)...etc.

**Comment by Eccenux** [comment]
One request per issue, please. Keep in mind that I don't actively develop this project, so I'm not currently open to any major changes.
