### ISSUE TITLE
Corruption of images

### ISSUE THREAD

**Issue by ocgltd** [Eccenux/POBS#3]
When pobs copies non-PHP files from the source to the target directory structure, it appears to corrupt the image files (*.gif and *.png confirmed).

**Comment by Eccenux** [comment]
All files not matched for obfuscation are copied with a simple `copy` function. So either your PHP installation is currupt or you've changed settings to obfuscate png files.

At the top of the log you should see something like:
```
Execute POBS : "./io/in" => "./io/out"
  
+ Scanning File: something.php
 - Copy Filename: some_image.jpg
 - Copy Filename: other_image.gif"
```

**Comment by ocgltd** [comment]
My settings file includes:
 $FileExtArray = array("php", "ee");
so I don't see why the graphics files would be processed.

**Comment by Eccenux** [comment]
Cannot confirm. As said - image files should only be copied and in log you should see `Copy Filename: some_image.png`.
